version: '2'
file-lines:
  enabled: true
  config: 
    threshold: 250
method-complexity:
  enabled: true
  config:
    threshold: 5
method-lines:
  enabled: true
  config:
    threshold: 30
return-statements:
  enabled: true
  config:
    threshold: 6
exclude_patterns:
  - '**/database/*'
  - '**/*.spec.js'
  - '**/__mocks__/'
